require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactinformationsController do

  # This should return the minimal set of attributes required to create a valid
  # Contactinformation. As you add validations to Contactinformation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all contactinformations as @contactinformations" do
      contactinformation = Contactinformation.create! valid_attributes
      get :index
      assigns(:contactinformations).should eq([contactinformation])
    end
  end

  describe "GET show" do
    it "assigns the requested contactinformation as @contactinformation" do
      contactinformation = Contactinformation.create! valid_attributes
      get :show, :id => contactinformation.id.to_s
      assigns(:contactinformation).should eq(contactinformation)
    end
  end

  describe "GET new" do
    it "assigns a new contactinformation as @contactinformation" do
      get :new
      assigns(:contactinformation).should be_a_new(Contactinformation)
    end
  end

  describe "GET edit" do
    it "assigns the requested contactinformation as @contactinformation" do
      contactinformation = Contactinformation.create! valid_attributes
      get :edit, :id => contactinformation.id.to_s
      assigns(:contactinformation).should eq(contactinformation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contactinformation" do
        expect {
          post :create, :contactinformation => valid_attributes
        }.to change(Contactinformation, :count).by(1)
      end

      it "assigns a newly created contactinformation as @contactinformation" do
        post :create, :contactinformation => valid_attributes
        assigns(:contactinformation).should be_a(Contactinformation)
        assigns(:contactinformation).should be_persisted
      end

      it "redirects to the created contactinformation" do
        post :create, :contactinformation => valid_attributes
        response.should redirect_to(Contactinformation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contactinformation as @contactinformation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contactinformation.any_instance.stub(:save).and_return(false)
        post :create, :contactinformation => {}
        assigns(:contactinformation).should be_a_new(Contactinformation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contactinformation.any_instance.stub(:save).and_return(false)
        post :create, :contactinformation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contactinformation" do
        contactinformation = Contactinformation.create! valid_attributes
        # Assuming there are no other contactinformations in the database, this
        # specifies that the Contactinformation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contactinformation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => contactinformation.id, :contactinformation => {'these' => 'params'}
      end

      it "assigns the requested contactinformation as @contactinformation" do
        contactinformation = Contactinformation.create! valid_attributes
        put :update, :id => contactinformation.id, :contactinformation => valid_attributes
        assigns(:contactinformation).should eq(contactinformation)
      end

      it "redirects to the contactinformation" do
        contactinformation = Contactinformation.create! valid_attributes
        put :update, :id => contactinformation.id, :contactinformation => valid_attributes
        response.should redirect_to(contactinformation)
      end
    end

    describe "with invalid params" do
      it "assigns the contactinformation as @contactinformation" do
        contactinformation = Contactinformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contactinformation.any_instance.stub(:save).and_return(false)
        put :update, :id => contactinformation.id.to_s, :contactinformation => {}
        assigns(:contactinformation).should eq(contactinformation)
      end

      it "re-renders the 'edit' template" do
        contactinformation = Contactinformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contactinformation.any_instance.stub(:save).and_return(false)
        put :update, :id => contactinformation.id.to_s, :contactinformation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contactinformation" do
      contactinformation = Contactinformation.create! valid_attributes
      expect {
        delete :destroy, :id => contactinformation.id.to_s
      }.to change(Contactinformation, :count).by(-1)
    end

    it "redirects to the contactinformations list" do
      contactinformation = Contactinformation.create! valid_attributes
      delete :destroy, :id => contactinformation.id.to_s
      response.should redirect_to(contactinformations_url)
    end
  end

end
